// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1JccLnlK1p0sVvHIhjBAdTkFFSzv9nUE',
    appId: '1:948270797075:web:87966f1b55fb9907e48ae6',
    messagingSenderId: '948270797075',
    projectId: 'case-management-a13ea',
    authDomain: 'case-management-a13ea.firebaseapp.com',
    storageBucket: 'case-management-a13ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJyLhjliFe2jQot_XVViQeJDAS8Ah68Y',
    appId: '1:948270797075:android:364f9c6e904a6e32e48ae6',
    messagingSenderId: '948270797075',
    projectId: 'case-management-a13ea',
    storageBucket: 'case-management-a13ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQh9KeX7k8mauxWraWq5BZbuKigX2Q2A',
    appId: '1:948270797075:ios:3a3a24f5e7f95038e48ae6',
    messagingSenderId: '948270797075',
    projectId: 'case-management-a13ea',
    storageBucket: 'case-management-a13ea.firebasestorage.app',
    iosBundleId: 'com.example.caseManagementProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQh9KeX7k8mauxWraWq5BZbuKigX2Q2A',
    appId: '1:948270797075:ios:3a3a24f5e7f95038e48ae6',
    messagingSenderId: '948270797075',
    projectId: 'case-management-a13ea',
    storageBucket: 'case-management-a13ea.firebasestorage.app',
    iosBundleId: 'com.example.caseManagementProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1JccLnlK1p0sVvHIhjBAdTkFFSzv9nUE',
    appId: '1:948270797075:web:fbbe5b9fc5f2c5d3e48ae6',
    messagingSenderId: '948270797075',
    projectId: 'case-management-a13ea',
    authDomain: 'case-management-a13ea.firebaseapp.com',
    storageBucket: 'case-management-a13ea.firebasestorage.app',
  );
}
